#!/bin/bash

# ezpi4me
# Written by Huan Truong <htruong@tnhh.net>, 2018
# This script is licensed under GNU Public License v3

if [ -f coreboot.bin ]; then
    echo "Notice: I'm cleaning the coreboot.bin file."
    python /usr/local/bin/me_cleaner.py -O bios_cleaned.bin coreboot.bin
else
    echo "Notice: I'm cleaning the bios_backup.bin file."
    python /usr/local/bin/me_cleaner.py -O bios_cleaned.bin bios_backup.bin
fi
